# Generated by Django 5.2.6 on 2025-09-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número da vaga', max_length=10, unique=True, verbose_name='Número')),
                ('tamanho', models.CharField(help_text='Tamanho da vaga (ex: Pequena, Média, Grande)', max_length=20, verbose_name='Tamanho')),
                ('andar', models.CharField(choices=[('A', '1º Andar'), ('B', '2º Andar'), ('C', '3º Andar')], help_text='Andar da vaga', max_length=1, verbose_name='Andar')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
