# Generated by Django 5.2.6 on 2025-10-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.CharField(help_text='Número da vaga', max_length=10, verbose_name='Número'),
        ),
    ]
