# Generated by Django 5.2.6 on 2025-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0002_alter_vaga_numero'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vaga',
            constraint=models.UniqueConstraint(fields=('numero', 'andar'), name='unique_numero_andar'),
        ),
    ]
