# Generated by Django 5.2.6 on 2025-10-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0003_vaga_unique_numero_andar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='tamanho',
            field=models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Medio'), ('Grande', 'Grande')], help_text='Tamanho da vaga (ex: Pequena, Média, Grande)', max_length=20, verbose_name='Tamanho'),
        ),
    ]
