# Generated by Django 5.2.6 on 2025-11-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0004_alter_vaga_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('Livre', 'Livre'), ('Ocupada', 'Ocupada')], default='Livre', help_text='Status atual da vaga', max_length=10, verbose_name='Status'),
        ),
    ]
