# Generated by Django 5.2.6 on 2025-11-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0005_vaga_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='tamanho',
        ),
    ]
