# Generated by Django 5.2.6 on 2025-10-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estadia')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='CPF completo', max_length=11, unique=True, verbose_name='CPF')),
                ('fone', models.CharField(help_text='Número de telefone', max_length=11, unique=True, verbose_name='Fone')),
                ('cargo', models.CharField(choices=[('Gerente', 'Gerente'), ('Atendente', 'Atendente')], max_length=20, verbose_name='Cargo')),
                ('salario', models.DecimalField(decimal_places=2, help_text='Salário do funcionário', max_digits=10, verbose_name='Salário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
