# Generated by Django 5.2.6 on 2025-10-16 17:08

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='media/', variations={'thumb': {'crop': True, 'height': 150, 'width': 150}}, verbose_name='Foto'),
        ),
    ]
