# Generated by Django 5.2.6 on 2025-10-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('pessoa', '0004_alter_cliente_email'),
        ('veiculo', '0003_alter_veiculo_options_veiculo_dono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(help_text='Data e hora de entrada', verbose_name='Entrada')),
                ('saida_prevista', models.DateTimeField(help_text='Data e hora prevista de saída', verbose_name='Saída Prevista')),
                ('saida', models.DateTimeField(blank=True, help_text='Data e hora real de saída', null=True, verbose_name='Saída Real')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8, verbose_name='Valor')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pessoa.cliente', verbose_name='Dono')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='funcionarios.funcionario', verbose_name='Funcionario')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='veiculo.veiculo', verbose_name='Placa')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-entrada'],
            },
        ),
    ]
