# Generated by Django 5.2.6 on 2025-10-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('EA', 'Em Andamento'), ('FI', 'Finalizado'), ('CA', 'Cancelado')], default='EA', max_length=2, verbose_name='Status'),
        ),
    ]
