# Generated by Django 5.2.6 on 2025-11-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
