# Generated by Django 5.2.6 on 2025-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_agendamento_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
