# Generated by Django 5.2.6 on 2025-11-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_agendamento_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-entrada'], 'permissions': (('fechar_agendamento', 'Permite fazer o fechamento de um agendamento'),), 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
