# Generated by Django 5.2.6 on 2025-11-15 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_alter_agendamento_options'),
        ('pessoa', '0005_cliente_empresa'),
        ('veiculo', '0004_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pessoa.cliente', verbose_name='Responsavel'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='placa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='veiculo.veiculo', verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='saida_prevista',
            field=models.DateTimeField(help_text='Data e hora prevista de saída (Saida não pode ser antes da ENTRADA)', verbose_name='Saída Prevista'),
        ),
    ]
