# Generated by Django 5.2.8 on 2025-11-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_agendamento_dono_alter_agendamento_placa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
