# Generated by Django 5.2.6 on 2025-10-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Empresa', max_length=50, unique=True, verbose_name='Nome')),
                ('cnpj', models.CharField(help_text='CNPJ da Empresa', max_length=18, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email da Empresa', max_length=100, null=True, unique=True, verbose_name='Email')),
                ('fone', models.CharField(help_text='Fone da Empresa', max_length=20, unique=True, verbose_name='Fone')),
            ],
            options={
                'verbose_name': 'Juridico',
                'verbose_name_plural': 'Juridicos',
            },
        ),
    ]
