# Generated by Django 5.2.6 on 2025-09-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='CPF completo', max_length=11, unique=True, verbose_name='CPF')),
                ('fone', models.CharField(help_text='Número de telefone', max_length=11, unique=True, verbose_name='Fone')),
                ('endereco', models.CharField(help_text='Endereço Completo', max_length=100, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
