# Generated by Django 5.2.6 on 2025-10-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='email@exemplo.com', help_text='Email completo', max_length=254, verbose_name='Email'),
        ),
    ]
