# Generated by Django 5.2.6 on 2025-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Email completo', max_length=254, null=True, verbose_name='Email'),
        ),
    ]
