# Generated by Django 5.2.6 on 2025-10-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email'),
        ),
    ]
