# Generated by Django 5.2.6 on 2025-10-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0001_initial'),
        ('pessoa', '0004_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='juridico.juridico'),
        ),
    ]
