# Generated by Django 5.2.6 on 2025-10-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('idEstadia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estadia')),
                ('entrada', models.DateTimeField(help_text='Data e hora de entrada', verbose_name='Entrada')),
                ('saida', models.DateTimeField(help_text='Data e hora de saída', verbose_name='Saída')),
            ],
            options={
                'verbose_name': 'Estadia',
                'verbose_name_plural': 'Estadias',
            },
        ),
    ]
