# Generated by Django 5.2.6 on 2025-10-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='saida',
            field=models.DateTimeField(blank=True, help_text='Data e hora de saída', null=True, verbose_name='Saída'),
        ),
    ]
