# Generated by Django 5.2.6 on 2025-10-03 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadia', '0004_alter_estadia_vaga_alter_estadia_veiculo'),
        ('vaga', '0004_alter_vaga_tamanho'),
        ('veiculo', '0003_alter_veiculo_options_veiculo_dono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='vaga.vaga', verbose_name='Vaga'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='veiculo.veiculo', verbose_name='Veículo'),
        ),
    ]
