# Generated by Django 5.2.6 on 2025-10-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadia', '0005_alter_estadia_vaga_alter_estadia_veiculo'),
        ('vaga', '0004_alter_vaga_tamanho'),
        ('veiculo', '0003_alter_veiculo_options_veiculo_dono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='vaga',
            field=models.ForeignKey(blank=True, help_text='Vaga que será ocupada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='vaga.vaga', verbose_name='Vaga'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='veiculo',
            field=models.ForeignKey(blank=True, help_text='Veiculo para ser estacionado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='veiculo.veiculo', verbose_name='Veículo'),
        ),
        migrations.AddConstraint(
            model_name='estadia',
            constraint=models.UniqueConstraint(condition=models.Q(('saida__isnull', True)), fields=('vaga',), name='unique_vaga_ativa'),
        ),
        migrations.AddConstraint(
            model_name='estadia',
            constraint=models.UniqueConstraint(condition=models.Q(('saida__isnull', True)), fields=('veiculo',), name='unique_veiculo_ativo'),
        ),
    ]
