# Generated by Django 5.2.6 on 2025-11-10 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadia', '0006_alter_estadia_vaga_alter_estadia_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Finalizada', 'Finalizada')], default='Em andamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='estadia',
            name='entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de entrada', verbose_name='Entrada'),
        ),
    ]
