# Generated by Django 5.2.6 on 2025-11-10 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadia', '0007_estadia_status_alter_estadia_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='entrada',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora de entrada', null=True, verbose_name='Entrada'),
        ),
    ]
