# Generated by Django 5.2.6 on 2025-11-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadia', '0008_alter_estadia_entrada'),
        ('veiculo', '0004_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='veiculo',
            field=models.OneToOneField(blank=True, help_text='Veículo que será estacionado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadia', to='veiculo.veiculo', verbose_name='Veículo'),
        ),
    ]
