# Generated by Django 5.2.6 on 2025-09-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa do Veiculo', max_length=10, unique=True, verbose_name='Placa')),
                ('tipo', models.CharField(help_text='Tipo de Veiculo', max_length=10, verbose_name='Tipo de Veiculo')),
            ],
        ),
    ]
