# Generated by Django 5.2.6 on 2025-09-30 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
        ('veiculo', '0002_alter_veiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='pessoa.cliente'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(help_text='Placa do veículo', max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Caminhão', 'Caminhão')], max_length=20, verbose_name='Tipo de Veículo'),
        ),
    ]
