# Generated by Django 5.2.6 on 2025-11-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_alter_veiculo_options_veiculo_dono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(help_text='Placa do veículo', max_length=5, unique=True, verbose_name='Placa'),
        ),
    ]
