# Generated by Django 5.2.6 on 2025-10-29 17:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadia', '0006_alter_estadia_vaga_alter_estadia_veiculo_and_more'),
        ('pessoa', '0005_cliente_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('idPagamento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pagamento')),
                ('valorHora', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6, verbose_name='Valor Hora')),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4, verbose_name='Multa (%)')),
                ('metodo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito'), ('P', 'Pix')], help_text='Selecione o método de pagamento (Débito, Crédito ou Pix)', max_length=1, verbose_name='Método de Pagamento')),
                ('placa', models.CharField(help_text='Placa do veículo', max_length=10, verbose_name='Placa')),
                ('valorFinal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Valor Final')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('multa_aplicada', models.BooleanField(default=False, verbose_name='Aplicar Multa?')),
                ('dono', models.ForeignKey(help_text='Cliente responsável pelo pagamento', on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pessoa.cliente', verbose_name='Dono')),
                ('estadia', models.OneToOneField(help_text='Estadia associada ao pagamento', on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='estadia.estadia', verbose_name='Estadia')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
