# Generated by Django 5.2.6 on 2025-10-30 17:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Desconto (R$)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Valor da Multa (R$)'),
        ),
    ]
