# Generated by Django 5.2.6 on 2025-10-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_pagamento_valor_desconto_pagamento_valor_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído')], default='P', max_length=1, verbose_name='Status do pagamento'),
        ),
    ]
