# Generated by Django 5.2.6 on 2025-11-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_pagamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='valorHora',
        ),
    ]
