# Generated by Django 5.2.6 on 2025-11-15 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValorHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_vigente', models.DecimalField(decimal_places=2, help_text='Valor atual da hora de estacionamento', max_digits=6, verbose_name='Valor da Hora (R$)')),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento em que o valor foi atualizado', verbose_name='Data da Alteração')),
            ],
            options={
                'verbose_name': 'Valor da Hora',
                'verbose_name_plural': 'Valores da Hora',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
